import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ChevronRight, ExternalLink, UploadCloud, XCircle, ShieldCheck } from "lucide-react";
import { RoleGuard } from "@/roles/components/RoleGuard";
import { UploadDropzone } from "@/documents/components/UploadDropzone";
import { SecurityAccessContextPanel, SupportedFilesPanel, UploadWorkflowPanel } from "@/documents/components/UploadSidePanels";
import { useAuth } from "@/auth/auth-context";
import type { DocumentFileValidation, DocumentUploadDraft } from "@/api/types";
import { getDocumentServiceStatus, getDocumentUploadConstraints, getDocumentUploadVocabulary, getUploadWorkflowStages, prepareDocumentUpload, submitDocumentUpload, validateDocumentFile } from "@/api/workspace-service";
import { PageHeader } from "@/shared/components/ui/page-header";
import { StatusPill } from "@/shared/components/ui/status-pill";

export const Route = createFileRoute("/_workspace/upload")({ head: () => ({ meta: [{ title: "Upload Document — NeroxaAI" }, { name: "description", content: "Controlled enterprise document ingestion with access metadata." }, { name: "robots", content: "noindex" }] }), component: UploadRoute });
function UploadRoute() { return <RoleGuard role="ADMIN" permission="documents:upload"><UploadDocumentPage /></RoleGuard>; }
const fieldClass = "h-10 w-full rounded-xl border border-hairline bg-secondary/35 px-3 text-[12px] text-foreground placeholder:text-muted-foreground/75 outline-none transition-colors focus-visible:border-primary/60";
function FieldLabel({ children, required }: { children: React.ReactNode; required?: boolean }) { return <span className="block text-[10.5px] font-medium uppercase tracking-[0.08em] text-muted-foreground">{children}{required ? <span className="ml-0.5 text-destructive">*</span> : null}</span>; }
function FieldHint({ error, hint }: { error?: string; hint: string }) { return <span className={error ? "block text-[10.5px] text-destructive" : "block text-[10.5px] text-muted-foreground"}>{error ?? hint}</span>; }
type NoticeState = { kind: "none" } | { kind: "success"; message: string } | { kind: "error"; message: string };

function UploadDocumentPage() {
  const { session } = useAuth(); const admin = session?.user ?? null; const navigate = useNavigate(); const queryClient = useQueryClient(); const constraints = getDocumentUploadConstraints(); const workflow = getUploadWorkflowStages(); const vocabulary = getDocumentUploadVocabulary();
  const serviceStatus = useQuery({ queryKey: ["document-service-status"], queryFn: getDocumentServiceStatus, refetchInterval: 30000 }); const [file, setFile] = useState<File | null>(null); const [validation, setValidation] = useState<DocumentFileValidation | null>(null); const [showErrors, setShowErrors] = useState(false); const [notice, setNotice] = useState<NoticeState>({ kind: "none" }); const [uploading, setUploading] = useState(false); const [draft, setDraft] = useState<DocumentUploadDraft>({ name: "", department: "", documentType: "", accessScopeLabel: "", description: "" });
  const preparation = useMemo(() => prepareDocumentUpload({ draft, file, admin }), [draft, file, admin]); const status = serviceStatus.data ?? null; const serviceConnected = status?.state === "connected"; const canSubmit = preparation.ready && serviceConnected && !uploading;
  const update = <K extends keyof DocumentUploadDraft>(key: K, value: DocumentUploadDraft[K]) => { setDraft((current) => ({ ...current, [key]: value })); setNotice({ kind: "none" }); };
  const selectFile = (next: File) => { const result = validateDocumentFile(next); setFile(next); setValidation(result); setNotice({ kind: "none" }); if (result.valid && !draft.name.trim()) { const base = next.name.replace(/\.[^.]+$/, "").replace(/[_-]+/g, " ").trim(); if (base) update("name", base); } };
  const clearFile = () => { setFile(null); setValidation(null); setNotice({ kind: "none" }); }; const resetForm = () => { setFile(null); setValidation(null); setShowErrors(false); setDraft({ name: "", department: "", documentType: "", accessScopeLabel: "", description: "" }); };
  const submit = async () => { setShowErrors(true); if (!preparation.ready || !preparation.payload || !file) return; setUploading(true); setNotice({ kind: "none" }); try { const result = await submitDocumentUpload(preparation.payload, file); if (result.accepted) { setNotice({ kind: "success", message: result.message }); for (const key of ["admin-documents", "admin-document-filters", "admin-document-overview", "admin-metrics", "documents", "document-filter-options", "recent-documents", "knowledge-overview"]) void queryClient.invalidateQueries({ queryKey: [key] }); resetForm(); } else setNotice({ kind: "error", message: result.message }); } catch (err: any) { setNotice({ kind: "error", message: err?.message || "An unexpected error occurred." }); } finally { setUploading(false); } };
  const errors = showErrors ? preparation.fieldErrors : {};
  return <div className="space-y-5">
    <PageHeader eyebrow="Controlled ingestion" title="Upload document" description="Prepare an enterprise knowledge source with ownership, document type, and retrieval access scope before indexing." actions={<StatusPill tone="accent" icon={<ShieldCheck className="size-3" />}>Admin ingestion</StatusPill>} />
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_300px] xl:items-start">
      <div className="space-y-4"><section className="rounded-2xl border border-hairline bg-card/55 p-4 shadow-sm backdrop-blur-xl"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-display text-sm font-semibold text-foreground">1. Select source</h2><p className="mt-0.5 text-[10.5px] text-muted-foreground">Upload a supported file for ingestion.</p></div><StatusPill tone={validation?.valid ? "success" : "neutral"}>{file ? (validation?.valid ? "Validated" : "Needs attention") : "Waiting for file"}</StatusPill></div><UploadDropzone constraints={constraints} file={file} validation={validation} onSelect={selectFile} onClear={clearFile} /></section>
      <section className="rounded-2xl border border-hairline bg-card/55 p-4 shadow-sm backdrop-blur-xl"><div className="mb-4"><h2 className="font-display text-sm font-semibold text-foreground">2. Define knowledge metadata</h2><p className="mt-0.5 text-[10.5px] text-muted-foreground">These fields control organization and retrieval visibility.</p></div><div className="grid gap-4 lg:grid-cols-3"><label className="space-y-1.5"><FieldLabel required>Document name</FieldLabel><input value={draft.name} onChange={(e) => update("name", e.target.value)} placeholder="Information Security Policy" maxLength={160} className={fieldClass} /><FieldHint error={errors.name} hint="Clear searchable name." /></label><label className="space-y-1.5"><FieldLabel required>Department</FieldLabel><select value={draft.department} onChange={(e) => update("department", e.target.value)} className={fieldClass}><option value="">Select department</option>{vocabulary.departments.map((v) => <option key={v} value={v}>{v}</option>)}</select><FieldHint error={errors.department} hint="Owning department." /></label><label className="space-y-1.5"><FieldLabel required>Document type</FieldLabel><select value={draft.documentType} onChange={(e) => update("documentType", e.target.value)} className={fieldClass}><option value="">Select type</option>{vocabulary.documentTypes.map((v) => <option key={v} value={v}>{v}</option>)}</select><FieldHint error={errors.documentType} hint="Knowledge source type." /></label></div><div className="mt-4 grid gap-4 lg:grid-cols-3"><label className="space-y-1.5"><FieldLabel>Access scope</FieldLabel><select value={draft.accessScopeLabel} onChange={(e) => update("accessScopeLabel", e.target.value)} className={fieldClass}><option value="">Auto · department scope</option>{vocabulary.accessScopes.map((v) => <option key={v.label} value={v.label}>{v.label}</option>)}</select><FieldHint error={errors.accessScopeLabel} hint="Who may retrieve this source." /></label><label className="space-y-1.5 lg:col-span-2"><FieldLabel>Description</FieldLabel><textarea value={draft.description} onChange={(e) => update("description", e.target.value)} rows={3} maxLength={1000} placeholder="Purpose or summary for administrators." className="w-full resize-none rounded-xl border border-hairline bg-secondary/35 px-3 py-2 text-[12px] outline-none focus-visible:border-primary/60" /><FieldHint error={errors.description} hint="Optional administrative context." /></label></div></section>
      <section className="rounded-2xl border border-hairline bg-card/55 p-4 shadow-sm backdrop-blur-xl"><div className="mb-3 flex items-center justify-between"><div><h2 className="font-display text-sm font-semibold">3. Validate & index</h2><p className="mt-0.5 text-[10.5px] text-muted-foreground">Files are parsed, chunked, embedded, and indexed after submission.</p></div><StatusPill tone={serviceConnected ? "success" : "warning"}>{status?.label ?? "Checking service"}</StatusPill></div>{notice.kind !== "none" ? <div className={`mb-3 flex items-start gap-2 rounded-xl border px-3 py-2.5 text-[11.5px] ${notice.kind === "success" ? "border-emerald-500/30 bg-emerald-500/[0.06] text-emerald-300" : "border-destructive/30 bg-destructive/[0.06] text-destructive"}`}>{notice.kind === "success" ? <CheckCircle2 className="size-4" /> : <XCircle className="size-4" />}{notice.message}</div> : null}{!serviceConnected ? <div className="mb-3 flex gap-2.5 rounded-xl border border-amber-400/20 bg-amber-400/[0.05] px-3 py-2.5"><AlertTriangle className="mt-0.5 size-4 shrink-0 text-amber-400" /><p className="text-[11px] leading-relaxed text-muted-foreground">{status?.detail ?? "The document service has not reported a connected state yet."}</p></div> : null}<div className="flex flex-wrap justify-between gap-2"><button type="button" onClick={() => navigate({ to: "/admin/documents" })} className="h-9 rounded-xl border border-hairline bg-secondary/40 px-3.5 text-[11.5px] hover:bg-accent/60">Cancel</button><button id="upload-document-btn" type="button" onClick={submit} disabled={!canSubmit} className="h-9 rounded-xl bg-primary px-4 text-[11.5px] font-medium text-primary-foreground shadow-sm transition-all hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-40">{uploading ? "Indexing…" : "Upload & index"}</button></div></section></div>
      <aside className="space-y-3 xl:sticky xl:top-[4.5rem]"><SecurityAccessContextPanel /><SupportedFilesPanel constraints={constraints} /><UploadWorkflowPanel stages={workflow} /></aside>
    </div>
  </div>;
}
