import type { AgentExecutionStep, AgentPlan, AssistantQueryRequest, AssistantQueryResponse, AssistantSource } from "./assistant-types";

const API_BASE_URL = import.meta.env["VITE_API_BASE_URL"] ?? "http://localhost:8000";

export interface AssistantQueryOptions { token?: string | null; signal?: AbortSignal; }
export interface AssistantSession { id:string; user_id:string; title:string; created_at:string; }
export interface AssistantMessage { id:string; session_id:string; role:string; content:string; sources:Record<string, unknown>[]|null; execution_metadata?:Record<string, unknown>|null; created_at:string; }

function buildHeaders(token?:string|null):HeadersInit { return { "Content-Type":"application/json", ...(token ? { Authorization:`Bearer ${token}` } : {}) }; }
async function parseError(response:Response,fallback:string):Promise<never>{ let detail=fallback; try{ const body=(await response.json()) as {detail?:string}; if(body.detail) detail=body.detail; }catch{} throw new Error(detail); }
function normalizeSource(source:Record<string,unknown>,index:number):AssistantSource{return{id:String(source["id"]??source["document_id"]??source["url"]??`source-${index}`),type:source["type"]==="web"?"web":"enterprise",title:String(source["title"]??source["document_title"]??source["filename"]??"Source"),url:typeof source["url"]==="string"?source["url"]:null,documentId:typeof source["document_id"]==="string"?source["document_id"]:null,page:typeof source["page"]==="number"?source["page"]:null,department:typeof source["department"]==="string"?source["department"]:null,snippet:typeof source["snippet"]==="string"?source["snippet"]:null};}
function normalizeAgentPlan(value:unknown):AgentPlan|null{if(!value||typeof value!=="object")return null;const plan=value as {steps?:unknown};if(!Array.isArray(plan.steps))return null;return{steps:plan.steps.filter((step):step is Record<string,unknown>=>!!step&&typeof step==="object").map(step=>({id:Number(step["id"]),type:String(step["type"]) as AgentExecutionStep["type"],task:String(step["task"]??""),toolName:typeof step["tool_name"]==="string"?step["tool_name"]:null,status:null}))};}
function normalizeResponse(request:AssistantQueryRequest,payload:Record<string,unknown>):AssistantQueryResponse{
 const rawSources=Array.isArray(payload["sources"])?payload["sources"]:[];
 const metadata=payload["execution_metadata"]&&typeof payload["execution_metadata"]==="object"?payload["execution_metadata"] as Record<string,unknown>:{};
 const value=(key:string)=>payload[key]??metadata[key];
 const rawSteps=Array.isArray(value("agent_steps"))?value("agent_steps") as unknown[]:Array.isArray(payload["steps"])?payload["steps"]:[];
 const route=String(value("route")??"enterprise");
 const normalizedRoute=["casual","enterprise","web","hybrid","tool","agent"].includes(route)?route as AssistantQueryResponse["route"]:"enterprise";
 const steps:AgentExecutionStep[]=rawSteps.filter((step):step is Record<string,unknown>=>!!step&&typeof step==="object").map(step=>({id:Number(step["step_id"]??step["id"]),type:String(step["type"]??"rag") as AgentExecutionStep["type"],task:String(step["task"]??""),toolName:typeof step["tool_name"]==="string"?step["tool_name"]:null,status:step["status"]==="failed"?"failed":"success"}));
 return{query:String(payload["query"]??request.query),answer:String(payload["answer"]??""),route:normalizedRoute,routeConfidence:typeof value("route_confidence")==="number"?value("route_confidence") as number:null,rewrittenQuery:typeof value("rewritten_query")==="string"?value("rewritten_query") as string:null,cached:value("cached")===true,model:typeof value("model")==="string"?value("model") as string:null,chunksRetrieved:typeof value("chunks_retrieved")==="number"?value("chunks_retrieved") as number:0,sources:rawSources.filter((source):source is Record<string,unknown>=>!!source&&typeof source==="object").map(normalizeSource),toolName:typeof value("tool_name")==="string"?value("tool_name") as string:null,toolStatus:value("tool_status")==="success"||value("tool_status")==="not_executed"?value("tool_status") as "success"|"not_executed":null,toolResult:value("tool_result")??null,agentPlan:normalizeAgentPlan(value("agent_plan")??payload["plan"]),agentSteps:steps,messageId:typeof payload["message_id"]==="string"?payload["message_id"]:null,createdAt:typeof payload["created_at"]==="string"?payload["created_at"]:null};
}

export async function createAssistantSession(title="New Conversation",options:AssistantQueryOptions={}):Promise<AssistantSession>{const response=await fetch(`${API_BASE_URL}/api/v1/chat/sessions`,{method:"POST",headers:buildHeaders(options.token),body:JSON.stringify({title}),...(options.signal ? { signal: options.signal } : {})});if(!response.ok)return parseError(response,`Could not create chat session (${response.status}).`);return await response.json() as AssistantSession;}
export async function sendAssistantMessage(sessionId:string,message:string,departmentFilter?:string|null,options:AssistantQueryOptions={}):Promise<AssistantMessage>{const response=await fetch(`${API_BASE_URL}/api/v1/chat/message`,{method:"POST",headers:buildHeaders(options.token),body:JSON.stringify({session_id:sessionId,message,department_filter:departmentFilter??null}),...(options.signal ? { signal: options.signal } : {})});if(!response.ok)return parseError(response,`Assistant request failed (${response.status}).`);return await response.json() as AssistantMessage;}
export async function queryAssistant(request:AssistantQueryRequest,options:AssistantQueryOptions={}):Promise<AssistantQueryResponse>{const response=await fetch(`${API_BASE_URL}/api/v1/query`,{method:"POST",headers:buildHeaders(options.token),body:JSON.stringify(request),...(options.signal ? { signal: options.signal } : {})});if(!response.ok)return parseError(response,`Assistant request failed (${response.status}).`);return normalizeResponse(request,await response.json() as Record<string,unknown>);}
export function normalizeAssistantMessage(request:AssistantQueryRequest,message:AssistantMessage):AssistantQueryResponse{return normalizeResponse(request,{query:request.query,answer:message.content,sources:message.sources??[],execution_metadata:message.execution_metadata,message_id:message.id,created_at:message.created_at});}
export function createAssistantAbortController():AbortController{return new AbortController();}
