/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WorkspaceAccessRouteImport } from './routes/_workspace.access'
import { Route as WorkspaceAccountRouteImport } from './routes/_workspace.account'
import { Route as WorkspaceAssistantRouteImport } from './routes/_workspace.assistant'
import { Route as WorkspaceAuditRouteImport } from './routes/_workspace.audit'
import { Route as WorkspaceDashboardRouteImport } from './routes/_workspace.dashboard'
import { Route as WorkspaceUploadRouteImport } from './routes/_workspace.upload'
import { Route as WorkspaceUsersRouteImport } from './routes/_workspace.users'
import { Route as WorkspaceAdminIndexRouteImport } from './routes/_workspace.admin.index'
import { Route as WorkspaceAdminDocumentsRouteImport } from './routes/_workspace.admin.documents'
import { Route as WorkspaceDocumentsIndexRouteImport } from './routes/_workspace.documents.index'
import { Route as WorkspaceDocumentsDocumentIdRouteImport } from './routes/_workspace.documents.$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceAccessRoute = WorkspaceAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAccountRoute = WorkspaceAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAssistantRoute = WorkspaceAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAuditRoute = WorkspaceAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDashboardRoute = WorkspaceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceUploadRoute = WorkspaceUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceUsersRoute = WorkspaceUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAdminIndexRoute = WorkspaceAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceAdminDocumentsRoute = WorkspaceAdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDocumentsIndexRoute = WorkspaceDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDocumentsDocumentIdRoute =
  WorkspaceDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => WorkspaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/access': typeof WorkspaceAccessRoute
  '/account': typeof WorkspaceAccountRoute
  '/assistant': typeof WorkspaceAssistantRoute
  '/audit': typeof WorkspaceAuditRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/upload': typeof WorkspaceUploadRoute
  '/users': typeof WorkspaceUsersRoute
  '/admin/documents': typeof WorkspaceAdminDocumentsRoute
  '/documents/$documentId': typeof WorkspaceDocumentsDocumentIdRoute
  '/admin/': typeof WorkspaceAdminIndexRoute
  '/documents/': typeof WorkspaceDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/access': typeof WorkspaceAccessRoute
  '/account': typeof WorkspaceAccountRoute
  '/assistant': typeof WorkspaceAssistantRoute
  '/audit': typeof WorkspaceAuditRoute
  '/dashboard': typeof WorkspaceDashboardRoute
  '/upload': typeof WorkspaceUploadRoute
  '/users': typeof WorkspaceUsersRoute
  '/admin/documents': typeof WorkspaceAdminDocumentsRoute
  '/documents/$documentId': typeof WorkspaceDocumentsDocumentIdRoute
  '/admin': typeof WorkspaceAdminIndexRoute
  '/documents': typeof WorkspaceDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/login': typeof LoginRoute
  '/_workspace/access': typeof WorkspaceAccessRoute
  '/_workspace/account': typeof WorkspaceAccountRoute
  '/_workspace/assistant': typeof WorkspaceAssistantRoute
  '/_workspace/audit': typeof WorkspaceAuditRoute
  '/_workspace/dashboard': typeof WorkspaceDashboardRoute
  '/_workspace/upload': typeof WorkspaceUploadRoute
  '/_workspace/users': typeof WorkspaceUsersRoute
  '/_workspace/admin/documents': typeof WorkspaceAdminDocumentsRoute
  '/_workspace/documents/$documentId': typeof WorkspaceDocumentsDocumentIdRoute
  '/_workspace/admin/': typeof WorkspaceAdminIndexRoute
  '/_workspace/documents/': typeof WorkspaceDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/access'
    | '/account'
    | '/assistant'
    | '/audit'
    | '/dashboard'
    | '/upload'
    | '/users'
    | '/admin/documents'
    | '/documents/$documentId'
    | '/admin/'
    | '/documents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/access'
    | '/account'
    | '/assistant'
    | '/audit'
    | '/dashboard'
    | '/upload'
    | '/users'
    | '/admin/documents'
    | '/documents/$documentId'
    | '/admin'
    | '/documents'
  id:
    | '__root__'
    | '/'
    | '/_workspace'
    | '/login'
    | '/_workspace/access'
    | '/_workspace/account'
    | '/_workspace/assistant'
    | '/_workspace/audit'
    | '/_workspace/dashboard'
    | '/_workspace/upload'
    | '/_workspace/users'
    | '/_workspace/admin/documents'
    | '/_workspace/documents/$documentId'
    | '/_workspace/admin/'
    | '/_workspace/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_workspace/access': {
      id: '/_workspace/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof WorkspaceAccessRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/account': {
      id: '/_workspace/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof WorkspaceAccountRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/assistant': {
      id: '/_workspace/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof WorkspaceAssistantRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/audit': {
      id: '/_workspace/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof WorkspaceAuditRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/dashboard': {
      id: '/_workspace/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof WorkspaceDashboardRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/upload': {
      id: '/_workspace/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof WorkspaceUploadRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/users': {
      id: '/_workspace/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof WorkspaceUsersRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/admin/': {
      id: '/_workspace/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof WorkspaceAdminIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/admin/documents': {
      id: '/_workspace/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof WorkspaceAdminDocumentsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/documents/': {
      id: '/_workspace/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof WorkspaceDocumentsIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/_workspace/documents/$documentId': {
      id: '/_workspace/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof WorkspaceDocumentsDocumentIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceAccessRoute: typeof WorkspaceAccessRoute
  WorkspaceAccountRoute: typeof WorkspaceAccountRoute
  WorkspaceAssistantRoute: typeof WorkspaceAssistantRoute
  WorkspaceAuditRoute: typeof WorkspaceAuditRoute
  WorkspaceDashboardRoute: typeof WorkspaceDashboardRoute
  WorkspaceUploadRoute: typeof WorkspaceUploadRoute
  WorkspaceUsersRoute: typeof WorkspaceUsersRoute
  WorkspaceAdminDocumentsRoute: typeof WorkspaceAdminDocumentsRoute
  WorkspaceDocumentsDocumentIdRoute: typeof WorkspaceDocumentsDocumentIdRoute
  WorkspaceAdminIndexRoute: typeof WorkspaceAdminIndexRoute
  WorkspaceDocumentsIndexRoute: typeof WorkspaceDocumentsIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceAccessRoute: WorkspaceAccessRoute,
  WorkspaceAccountRoute: WorkspaceAccountRoute,
  WorkspaceAssistantRoute: WorkspaceAssistantRoute,
  WorkspaceAuditRoute: WorkspaceAuditRoute,
  WorkspaceDashboardRoute: WorkspaceDashboardRoute,
  WorkspaceUploadRoute: WorkspaceUploadRoute,
  WorkspaceUsersRoute: WorkspaceUsersRoute,
  WorkspaceAdminDocumentsRoute: WorkspaceAdminDocumentsRoute,
  WorkspaceDocumentsDocumentIdRoute: WorkspaceDocumentsDocumentIdRoute,
  WorkspaceAdminIndexRoute: WorkspaceAdminIndexRoute,
  WorkspaceDocumentsIndexRoute: WorkspaceDocumentsIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
